name: packages_cli
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  args: any
  googleapis_auth: ^1.1.0
  googleapis: ^8.0.0
  http_retry: any
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
